// this code is generated by aspect dev tool.
import { AspTransaction } from "../lib/types/aspect/v1/AspTransaction";
import { Msg } from "../lib/types/msg";
import { stringToUint8Arrary } from "../lib/lib";

export class MyContract {
    public store100(msg: Msg): AspTransaction {
        // TODO, this should be encoded by the contract method "MyContract.deposit" and argument name = "Salary"
        let abiStr = "0x6057361d00000000000000000000000000000000000000000000000000000000000003e8"
        let input = stringToUint8Arrary(abiStr);

        let tx = new AspTransaction();
        tx.chainId = "";
        tx.nonce = 0;
        tx.gasTipCap = msg.maxPriorityFeePerGas;
        tx.gasFeeCap = msg.maxFeePerGas;
        tx.gasLimit = 0;
        tx.gasPrice = 0;
        tx.to = this._address;
        tx.value = msg.value;
        tx.input = input;
        tx.accessList = [];
        tx.blockHash = new Uint8Array(0);
        tx.blockNumber = 0;
        tx.from = msg.broker;
        tx.hash = new Uint8Array(0);
        tx.transactionIndex = 0;
        tx.type = 0;
        tx.v = new Uint8Array(0);
        tx.r = new Uint8Array(0);
        tx.s = new Uint8Array(0);
        return tx;
    }

    constructor(address: string = "") {
        this._address = address;
    }

    _address: string;
}
